In [2]:
import pandas as pd

In [4]:
# Reading data from csv file
sal = pd.read_csv('Salaries.csv')

In [7]:
sal.head(2)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN

In [8]:
sal.tail(2)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [9]:
sal.info()

<class 'pandas.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  str
 2   JobTitle          148654 non-null  str
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  str
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), str(3)
memory usage: 14.7 MB

In [10]:
sal.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='str')

### What is the average basepay

In [12]:
sal['BasePay'].mean()

np.float64(66325.44884048769)

### What is the highest amount of OvertimePay in the dataset?

In [13]:
sal['OvertimePay'].max()

np.float64(245131.88)

### What is the jobtile of JOSEPH DRISCOLL?

In [16]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
24,25,JOSEPH DRISCOLL,"CAPTAIN, FIRE SUPPRESSION",140546.86,97868.77,31909.28,NaN,270324.91,270324.91,2011,NaN,San Francisco,NaN

In [17]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

### How much does JOSEPH DRISCOLL make (including benefits)?

In [18]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

### What is the name of highest paid person (including benefits)?

In [20]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

### What was the average basepay for all employees per year

In [21]:
sal.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

### What are the top 5 most common jobs?

In [22]:
sal['JobTitle'].nunique()

2159

In [23]:
sal['JobTitle'].value_counts()

JobTitle
Transit Operator                  7036
Special Nurse                     4389
Registered Nurse                  3736
Public Svc Aide-Public Works      2518
Police Officer 3                  2421
                                  ...
Marina Associate Manager             1
Sr Cnselor, Juv Hall (SFERS)         1
Forensic Toxicologist Supervis       1
Conversion                           1
Cashier 3                            1
Name: count, Length: 2159, dtype: int64

In [24]:
sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

### How many people having word chief in their job title?

In [26]:
def chief_string(title):
    if 'chief' in title.lower(): #CHIEF, Chief, chief, cHiEf, chIEf, etc.
        return True
    else:
        return False

In [27]:
sal['JobTitle'].apply(lambda x : chief_string(x))

0         False
1         False
2         False
3         False
4          True
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Name: JobTitle, Length: 148654, dtype: bool

In [28]:
sum(sal['JobTitle'].apply(lambda x : chief_string(x)))

627